AWSTemplateFormatVersion: '2010-09-09'
Description: 'ETL System - IAM Database Authentication Users and Policies'

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name for resource naming'

  RDSEndpoint:
    Type: String
    Description: 'RDS Endpoint from Database Stack'

  RDSResourceId:
    Type: String
    Description: 'RDS Resource ID for IAM policy'

Resources:
  # テストユーザー1: 読み取り専用
  TestUserReadOnly:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub '${ProjectName}-test-user-readonly'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-test-user-readonly'
        - Key: Purpose
          Value: 'IAM DB Auth Testing - Read Only'

  # テストユーザー1のアクセスキー
  TestUserReadOnlyAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref TestUserReadOnly

  # テストユーザー1のポリシー（読み取り専用）
  TestUserReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ProjectName}-rds-readonly-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'rds-db:connect'
            Resource:
              - !Sub 'arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${RDSResourceId}/test_readonly'
      Users:
        - !Ref TestUserReadOnly

  # テストユーザー2: フルアクセス
  TestUserFullAccess:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub '${ProjectName}-test-user-fullaccess'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-test-user-fullaccess'
        - Key: Purpose
          Value: 'IAM DB Auth Testing - Full Access'

  # テストユーザー2のアクセスキー
  TestUserFullAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref TestUserFullAccess

  # テストユーザー2のポリシー（フルアクセス）
  TestUserFullAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ProjectName}-rds-fullaccess-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'rds-db:connect'
            Resource:
              - !Sub 'arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${RDSResourceId}/test_fullaccess'
      Users:
        - !Ref TestUserFullAccess

  # テストユーザー3: 特定テーブルのみアクセス
  TestUserLimited:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub '${ProjectName}-test-user-limited'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-test-user-limited'
        - Key: Purpose
          Value: 'IAM DB Auth Testing - Limited Access'

  # テストユーザー3のアクセスキー
  TestUserLimitedAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref TestUserLimited

  # テストユーザー3のポリシー（制限付きアクセス）
  TestUserLimitedPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ProjectName}-rds-limited-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'rds-db:connect'
            Resource:
              - !Sub 'arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${RDSResourceId}/test_limited'
      Users:
        - !Ref TestUserLimited

  # 管理者用ロール（EC2インスタンスプロファイル用）
  RDSAdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-rds-admin-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: RDSConnectPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'rds-db:connect'
                Resource:
                  - !Sub 'arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${RDSResourceId}/*'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-rds-admin-role'

  # EC2インスタンスプロファイル
  RDSAdminInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${ProjectName}-rds-admin-profile'
      Roles:
        - !Ref RDSAdminRole

Outputs:
  TestUserReadOnlyName:
    Description: Test User Read Only Name
    Value: !Ref TestUserReadOnly

  TestUserReadOnlyAccessKeyId:
    Description: Test User Read Only Access Key ID
    Value: !Ref TestUserReadOnlyAccessKey

  TestUserReadOnlySecretAccessKey:
    Description: Test User Read Only Secret Access Key
    Value: !GetAtt TestUserReadOnlyAccessKey.SecretAccessKey

  TestUserFullAccessName:
    Description: Test User Full Access Name
    Value: !Ref TestUserFullAccess

  TestUserFullAccessKeyId:
    Description: Test User Full Access Key ID
    Value: !Ref TestUserFullAccessKey

  TestUserFullAccessSecretAccessKey:
    Description: Test User Full Access Secret Access Key
    Value: !GetAtt TestUserFullAccessKey.SecretAccessKey

  TestUserLimitedName:
    Description: Test User Limited Name
    Value: !Ref TestUserLimited

  TestUserLimitedAccessKeyId:
    Description: Test User Limited Access Key ID
    Value: !Ref TestUserLimitedAccessKey

  TestUserLimitedSecretAccessKey:
    Description: Test User Limited Secret Access Key
    Value: !GetAtt TestUserLimitedAccessKey.SecretAccessKey

  RDSAdminRoleArn:
    Description: RDS Admin Role ARN
    Value: !GetAtt RDSAdminRole.Arn

  RDSAdminInstanceProfileArn:
    Description: RDS Admin Instance Profile ARN
    Value: !GetAtt RDSAdminInstanceProfile.Arn