CREATE TABLE IF NOT EXISTS sfc_assets (
    -- 基本情報
    id VARCHAR(18) NOT NULL,
    contact_id VARCHAR(18),
    account_id VARCHAR(18),
    parent_id VARCHAR(18),
    root_asset_id VARCHAR(18),
    product2_id VARCHAR(18),
    product_code VARCHAR(255) NOT NULL,
    product_family VARCHAR(40),
    product_description TEXT,
    is_competitor_product BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- システム情報
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_id VARCHAR(18) NOT NULL,
    last_modified_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by_id VARCHAR(18) NOT NULL,
    system_modstamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    currency_iso_code VARCHAR(10),
    
    -- 装置情報
    name VARCHAR(255) NOT NULL,
    serial_number VARCHAR(80),
    install_date DATE,
    manufacture_date DATE,
    status_reason VARCHAR(255),
    uuid UUID NOT NULL,
    external_identifier VARCHAR(255),
    purchase_date DATE,
    usage_end_date DATE,
    status VARCHAR(50) NOT NULL,
    
    -- デジタルアセット情報
    digital_asset_status NUMERIC(16,2),
    sum_down_time NUMERIC(16,2),
    sum_unplanned_down_time NUMERIC,
    uptime_record_start TIMESTAMP WITH TIME ZONE,
    uptime_record_end TIMESTAMP WITH TIME ZONE,
    average_uptime_per_day NUMERIC(16,2),
    availability NUMERIC,
    reliability NUMERIC,
    
    -- 価格・数量情報
    price NUMERIC,
    quantity NUMERIC(10,2),
    description TEXT,
    
    -- 関連情報
    owner_id VARCHAR(18) NOT NULL,
    record_type_id VARCHAR(18),
    location_id VARCHAR(18),
    asset_provided_by_id VARCHAR(18),
    asset_serviced_by_id VARCHAR(18),
    is_internal BOOLEAN DEFAULT FALSE,
    asset_level VARCHAR(50),
    stock_keeping_unit VARCHAR(180),
    consequence_of_failure TEXT,
    
    -- 住所情報
    street VARCHAR(255),
    city VARCHAR(40),
    state VARCHAR(80),
    postal_code VARCHAR(20),
    country VARCHAR(80),
    latitude NUMERIC(3,15),
    longitude NUMERIC(3,15),
    geocode_accuracy VARCHAR(50),
    address TEXT,
    
    -- 最終閲覧・参照情報
    last_viewed_date TIMESTAMP WITH TIME ZONE,
    last_referenced_date TIMESTAMP WITH TIME ZONE,
    
    -- YMCカスタム項目（59-183）
    ymc_cust_line_c VARCHAR(255),
    ymc_cntr_no_c VARCHAR(16),
    ymc_ctr_name_c VARCHAR(64),
    ymc_file_server_link_c TEXT,
    ymc_lineseq_c VARCHAR(2),
    ymc_model01_c VARCHAR(50),
    ymc_model02_c VARCHAR(10),
    ymc_model3_c VARCHAR(10),
    ymc_model4_c VARCHAR(10),
    ymc_model5_c VARCHAR(10),
    ymc_model6_c VARCHAR(10),
    ymc_model7_c VARCHAR(10),
    ymc_model8_c VARCHAR(10),
    ymc_model9_c VARCHAR(10),
    ymc_model_c VARCHAR(80),
    ymc_serial_c VARCHAR(13),
    ymc_service_agency_c VARCHAR(255),
    ymc_suedate_c DATE,
    ymc_ship_date_c DATE,
    ymc_warranty_due_date_c DATE,
    ymc_flow_label_c TEXT,
    ymc_model_detail_c TEXT,
    ymc_account_code_c TEXT,
    ymc_account_24h_c VARCHAR(255),
    ymc_account_maintenance_c VARCHAR(255),
    ymc_account_remote_c VARCHAR(255),
    ymc_account_soft_c VARCHAR(255),
    ymc_account_c VARCHAR(255),
    ymc_agency_confirmation_date2_c DATE,
    ymc_agency_confirmation_date_c DATE,
    ymc_alternative_machine_flag_c BOOLEAN DEFAULT FALSE,
    ymc_approval_status_c VARCHAR(50),
    ymc_area_c VARCHAR(255),
    ymc_base_confirmation_date2_c DATE,
    ymc_base_confirmation_date_c DATE,
    ymc_biko_c TEXT,
    ymc_cust_line_code_c TEXT,
    ymc_chk_date1_d1_c DATE,
    ymc_chk_date1_im_c DATE,
    ymc_cname_c VARCHAR(32),
    ymc_cntr_sn_c TEXT,
    ymc_comm_c VARCHAR(255),
    ymc_cre_date_c TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ymc_cre_prg_c VARCHAR(10),
    ymc_cre_tanto_text_c VARCHAR(255),
    ymc_cre_tanto_c VARCHAR(255),
    ymc_cust_name_c VARCHAR(255),
    ymc_cust_code_c TEXT,
    ymc_dealer_c VARCHAR(30),
    ymc_e_tanto_c VARCHAR(10),
    ymc_enduser_c VARCHAR(30),
    ymc_external_id_c VARCHAR(255),
    ymc_fa_flag_c BOOLEAN DEFAULT FALSE,
    ymc_eid_fqdn_c VARCHAR(100),
    ymc_hosyo_kanri_no_c VARCHAR(30),
    ymc_hosyo_type_c VARCHAR(255),
    ymc_im_confirmation_date2_c DATE,
    ymc_im_confirmation_date_c DATE,
    ymc_itopt_c VARCHAR(255),
    ymc_jyucyuno_c VARCHAR(6),
    ymc_kata_c VARCHAR(30),
    ymc_kbn_c VARCHAR(1),
    ymc_key_no_eda_c VARCHAR(1),
    ymc_key_serial_c VARCHAR(8),
    ymc_key_type_c VARCHAR(1),
    ymc_kigen_kanri_c VARCHAR(255),
    ymc_local_warranty_date_c DATE,
    ymc_local_warranty_no_c VARCHAR(10),
    ymc_new_maintenance_c BOOLEAN DEFAULT FALSE,
    ymc_odspjyno_c VARCHAR(8),
    ymc_orderno_c VARCHAR(29),
    ymc_r_c VARCHAR(6),
    ymc_refno_c VARCHAR(8),
    ymc_report_latest_expiration_date_c DATE,
    ymc_response_c DATE,
    ymc_smt_flag_c BOOLEAN DEFAULT FALSE,
    ymc_sammary_c TEXT,
    ymc_service_contract_c VARCHAR(255),
    ymc_setmaker_c VARCHAR(30),
    ymc_skbn_c VARCHAR(50),
    ymc_slider_sn_c TEXT,
    ymc_soft_ap_std_c VARCHAR(50),
    ymc_soft_ap_ver_c VARCHAR(7),
    ymc_soft_type_c VARCHAR(2),
    ymc_status_c VARCHAR(50),
    ymc_status_comment_c VARCHAR(43),
    ymc_suekbn_c VARCHAR(50),
    ymc_suetanto_c VARCHAR(255),
    ymc_syurui_c VARCHAR(50),
    ymc_tangikseq_c VARCHAR(3),
    ymc_tiku_c VARCHAR(50),
    ymc_tok_in_c VARCHAR(50),
    ymc_tokutyu_c TEXT,
    ymc_upd_date_c TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ymc_upd_prg_c VARCHAR(10),
    ymc_upd_tanto_text_c VARCHAR(255),
    ymc_upd_tanto_c VARCHAR(255),
    ymc_warranty_flag_c BOOLEAN DEFAULT FALSE,
    ymc_work_corresponding_person_c VARCHAR(255),
    ymc_work_person_c VARCHAR(255),
    ymc_youto_c VARCHAR(255),
    ymc_app_c VARCHAR(50),
    ymc_sysver_c VARCHAR(5),
    ymc_warranty_due_1monthleft_c DATE,
    ymc_warranty_due_2monthleft_c DATE,
    ymc_warranty_due_3monthleft_c DATE,
    ymc_warranty_due_4monthleft_c DATE,
    ymc_continuous_maintenance_c BOOLEAN DEFAULT FALSE,
    ymc_contract_asset_mail_table_c TEXT,
    ymc_cre_tanto_code_c TEXT,
    ymc_cust_name_code_c TEXT,
    ymc_status_classification_c TEXT,
    ymc_status_and_status_comment_c TEXT,
    ymc_suetanto_code_c TEXT,
    ymc_upd_tanto_code_c TEXT,
    ymc_account_code_for_search_c VARCHAR(255),
    ymc_cust_name_code_text_c VARCHAR(4),
    ymc_record_type_developer_name_c TEXT,
    ymc_product2_name_c TEXT,
    ymc_2nd_check_c TEXT,
    ymc_warranty_due_date_in_out_c TEXT,
    ymc_contact_information_c TEXT,
    ymc_1st_check_c TEXT,
    ymc_contact_information_copy_c TEXT,
    
    -- DWH管理カラム
    dwh_id INTEGER NOT NULL,
    dwh_operation_type_flag INTEGER NOT NULL,
    dwh_create_timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dwh_update_timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dwh_source_system_code VARCHAR(10) NOT NULL    

);
